theme: jekyll-theme-dinky
title: "Testitest"
description: "This is my personal demo page. Enjoy!"

github:
  is_project_page: false
  
nav:
  show: true
  home: /testitest/
  hobby: /testitest/watches/
  about: /testitest/about/
